[package]
name = "api"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.40"
diesel = { version = "1.4.6", features = ["postgres", "r2d2", "uuidv07"] }
dotenv = "0.15.0"
env_logger = "0.8.3"
r2d2 = "0.8.9"
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
actix-rt = "2.2.0"