[package]
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2021"
name = "api"
publish = false
resolver = "2"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[dependencies]
anyhow = "1.0.40"
argon2 = "0.2.0"
axum = "0.6"
base64 = "0.13.0"
casbin = { version = "2.0.9", default-features = false, features = ["runtime-tokio", "logging", "incremental", "explain"] }
chrono = {version = "0.4.19", features = ["serde"]}
diesel = { version = "2.0.3", default-features = false, features = ["postgres", "without-deprecated", "uuid", "chrono", "32-column-tables", "serde_json", "network-address"] }
diesel-async = { version = "0.2.0", features = ["bb8", "postgres"] }
diesel-derive-enum = { version = "2.0.1", features = ["postgres"] }
diesel_migrations = { version = "2.0.0", features = ["postgres"] }
dotenv = "0.15.0"
futures-util = "0.3.21"
h2 = "0.3.13"
handlebars = "4.3.3"
heck = "0.4.0"
http = "0.2.8"
hyper = "0.14.20"
ipnet = "2.7.1"
ipnetwork = "0.20"
jsonwebtoken = "7.2.0"
log = "0.4.14"
petname = "1.1.0"
pin-project = "1.0.11"
prost = "0.11.6"
prost-types = "0.11.6"
rand = "0.8.5"
rumqttc = "0.20.0"
sendgrid = {version = "0.17.4", default-features = false, features = ["rustls", "async"]}
serde = {version = "1.0.125", features = ["derive"]}
serde_json = { version = "1.0.81", features = ["raw_value"] }
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.24"
tokio = { version = "1.2.0", default-features = false, features = ["io-util", "sync", "macros", "sync", "rt-multi-thread"] }
tokio-stream = { version = "0.1.9", features = ["net"] }
toml = "0.5.9"
tonic = { version = "0.8.3", features = ["tls-roots"] }
tower = { version = "0.4", features = ["tokio", "tracing", "util"] }
tower-http = {version = "0.3.2", features = ["cors", "trace", "compression-gzip", "auth"]}
tracing = "0.1.34"
tracing-subscriber = {version = "0.3.11", features = ["env-filter"]}
uuid = {version = "1.2.1", features = ["serde", "v4"]}
validator = {version = "0.13.0", features = ["derive"]}

[dev-dependencies]
hyper = {version = "0.14.18", features = ["full"]}
temp-env = "0.3.1"
tempfile = "3.3.0"

[build-dependencies]
tonic-build = "0.8.3"
