[package]
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2018"
name = "api"
publish = false
resolver = "2"
version = "0.1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'

[dependencies]
axum = "0.5.4"
tokio = {version = "1.2.0", default-features = false, features = ["io-util", "sync", "macros"] }
tower-http = { version = "0.3.2", features = ["cors", "trace", "compression-gzip"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
angry-purple-tiger = "0.1.0"
anyhow = "1.0.40"
argon2 = "0.2.0"
chrono = {version = "0.4.19", features = ["serde"]}
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
log = "0.4.14"
petname = "1.1.0"
qrcode-generator = "4.1.1"
rand_core = {version = "0.6", features = ["std"]}
sendgrid = {version = "0.17.4", default-features = false, features = ["rustls", "async"]}
serde = {version = "1.0.125", features = ["derive"]}
serde_json = "1.0.81"
sqlx = {version = "0.5", features = ["postgres", "runtime-tokio-rustls", "migrate", "chrono", "uuid"]}
thiserror = "1.0.24"
uuid = {version = "0.8", features = ["serde", "v4"]}
validator = {version = "0.13.0", features = ["derive"]}
random-string = "1.0.0"

[dev-dependencies]
tower = { version = "0.4.12", features = ["util"] }
hyper = { version = "0.14.18", features = ["full"] }
