[package]
name = "api"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3.2"
anyhow = "1.0.40"
dotenv = "0.15.0"
env_logger = "0.8.3"
ipnetwork = { version = "0.17.0", features = ["serde"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.2", features = ["postgres", "runtime-actix-rustls","migrate", "time", "ipnetwork", "uuid" ] }
time = {version = "0.2.26", features = ["serde"] }
uuid = { version = "0.8", features = ["serde", "v4"] }

[dev-dependencies]
actix-rt = "2.2.0"
