[graph]
all-features = true

[advisories]
ignore = [
  "RUSTSEC-2024-0436" # paste crate is unmaintained
]

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CC0-1.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
]
exceptions = [
  { crate = "aws-lc-sys", allow = ["OpenSSL"] },
  { crate = "foldhash", allow = ["Zlib"] },
  { crate = "ring", allow = ["OpenSSL"] },
  { crate = "unicode-ident", allow = ["Unicode-DFS-2016"] },
]

[[licenses.clarify]]
crate = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
  { path = "LICENSE", hash = 0xbd0eed23 }
]

[licenses.private]
ignore = true
