[en]
html = """
<h1>Password Reset</h1>
<p>
    You have requested to reset your BlockJoy password. Please visit
    <a href="https://console.blockjoy.com/reset?t={{token}}">
        https://console.blockjoy.com/reset?t={{token}}
    </a>.
</p>
<br/><br/>
<p>Thank You!</p>
"""
text = """
Password Reset
                     
You have requested to reset your BlockJoy password. 
Please visit https://console.blockjoy.com/reset?t={{token}}".

Thank You!
"""

[nl]
html = """
<h1>Wachtwoord opnieuw instellen</h1>
<p>
    Je hebt aangevraagd om je wachtwoord opnieuw in te stellen. Ga hiervoor naar 
    <a href="https://console.blockjoy.com/reset?t={{token}}">
        https://console.blockjoy.com/reset?t={{token}}
    </a>.
</p>
<br/><br/>
<p>Dank!</p>
"""
text = """
Wachtwoord opnieuw instellen

Je hebt aangevraagd om je wachtwoord opnieuw in te stellen. Ga hiervoor naar
https://console.blockjoy.com/reset?t={{token}}

Dank!
"""
