apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: blockvisor-api-dev
  labels:
    app: blockvisor-api-dev
description: Blockvisor API Dev delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: testing
    profiles:
    - testing
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
requireApproval: false
gke:
  cluster: projects/blockjoy-dev/locations/us-east1-b/clusters/blockjoy-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: testing
  annotations: {}
  labels: {}
description: testing
requireApproval: false
gke:
  cluster: projects/blockjoy-testing/locations/us-east1-b/clusters/blockjoy-testing