apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: blockvisor-api-dev
  labels:
    app: blockvisor-api-dev
description: Blockvisor API Dev delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles:
    - dev
  - targetId: staging
    profiles:
    - staging
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
requireApproval: false
gke:
  cluster: projects/blockjoy-dev/locations/us-east1-b/clusters/blockjoy-dev
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
  annotations: {}
  labels: {}
description: staging
requireApproval: true
gke:
  cluster: projects/blockjoy-staging/locations/us-east1-b/clusters/blockjoy-staging