services:
  postgres:
    image: postgres:13-bookworm
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: blockvisor_db
      POSTGRES_USER: blockvisor
      POSTGRES_PASSWORD: password
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U blockvisor -d blockvisor_db'"]
      interval: 3s
      timeout: 1s
      retries: 3

  emqx:
    image: emqx/emqx-enterprise:5.3.0
    ports:
      - 21883:1883
    volumes:
      - ./emqx:/opt/emqx/etc

  vault:
    image: hashicorp/vault:1.17
    ports:
      - 28200:8200
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-root-token"
    cap_add:
      - IPC_LOCK

  vault-init:
    build: vault
    environment:
      VAULT_ADDR: "http://vault:8200"
    cap_add:
      - IPC_LOCK
