services:
  postgres:
    image: postgres:17.4
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: blockvisor_db
      POSTGRES_USER: blockvisor
      POSTGRES_PASSWORD: password
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockvisor -d blockvisor_db"]
      interval: 3s
      timeout: 1s
      retries: 3

  emqx:
    image: emqx/emqx-enterprise:5.8.5
    ports:
      - 21883:1883
    volumes:
      - ./emqx:/opt/emqx/etc

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - 23000:3000
    volumes:
      - ./metrics/grafana.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - 29090:9090
    volumes:
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - opentelemetry

  opentelemetry:
    image: otel/opentelemetry-collector-contrib:0.120.0
    command: ["--config=/etc/opentelemetry.yaml"]
    ports:
      - 24317:4317
      - 28889:8889
    volumes:
      - ./metrics/opentelemetry.yaml:/etc/opentelemetry.yaml
    depends_on:
      - loki
      - tempo

  loki:
    image: grafana/loki:3.4.2
    ports:
      - 23100:3100

  tempo:
    image: grafana/tempo:2.7.1
    ports:
      - 23200:3200
    command: -config.file=/etc/tempo/tempo.yaml
    volumes:
      - ./metrics/tempo.yaml:/etc/tempo/tempo.yaml
