services:
  postgres:
    image: postgres:17-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_DB: blockvisor_db
      POSTGRES_USER: blockvisor
      POSTGRES_PASSWORD: password
    ports:
      - 25432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blockvisor -d blockvisor_db"]
      interval: 3s
      timeout: 1s
      retries: 3

  emqx:
    image: emqx/emqx-enterprise:5.8.1
    ports:
      - 21883:1883
    volumes:
      - ./emqx:/opt/emqx/etc

  opentelemetry:
    image: otel/opentelemetry-collector:0.113.0
    command: ["--config=/etc/collector.yaml"]
    ports:
      - 24317:4317
      - 28889:8889
    volumes:
      - ./metrics/collector.yaml:/etc/collector.yaml

  prometheus:
    image: prom/prometheus:v3.0.0
    ports:
      - 29090:9090
    volumes:
      - ./metrics/prometheus.yaml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:11.3.1
    ports:
      - 23000:3000
    volumes:
      - ./metrics/grafana.yaml:/etc/grafana/provisioning/datasources/prometheus.yaml

  vault:
    image: hashicorp/vault:1.17
    ports:
      - 28200:8200
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-root-token"
    cap_add:
      - IPC_LOCK

  vault-init:
    build: vault
    environment:
      VAULT_ADDR: "http://vault:8200"
    cap_add:
      - IPC_LOCK
