apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: blockvisor
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: us-docker.pkg.dev/blockjoy-deployer/blockvisor-api/blockvisor-api
      context: ./
      docker:
        dockerfile: docker/Dockerfile
  local:
    push: true
profiles:
  - name: dev
    deploy:
      kustomize:
        paths:
          - ./kubernetes/dev
  - name: staging
    deploy:
      kustomize:
        paths:
          - ./kubernetes/staging
  - name: testing
    deploy:
      kustomize:
        paths:
          - ./kubernetes/testing
  - name: prod
    deploy:
      kustomize:
        paths:
          - ./kubernetes/prod
