apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blockvisor-api-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/blockjoy-staging/secrets/SENDGRID_API_KEY/versions/latest"
        path: "SENDGRID_API_KEY"
      - resourceName: "projects/blockjoy-staging/secrets/REFRESH_SECRET/versions/latest"
        path: "REFRESH_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/PWD_RESET_SECRET/versions/latest"
        path: "PWD_RESET_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/API_SERVICE_SECRET/versions/latest"
        path: "API_SERVICE_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/JWT_SECRET/versions/latest"
        path: "JWT_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/CONFIRMATION_SECRET/versions/latest"
        path: "CONFIRMATION_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/DATABASE_URL/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/blockjoy-staging/secrets/INVITATION_SECRET/versions/latest"
        path: "INVITATION_SECRET"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockvisor-api-sa
  annotations:
      iam.gke.io/gcp-service-account: gke-workload@blockjoy-staging.iam.gserviceaccount.com
---