apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blockvisor-api-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/blockjoy-staging/secrets/API_SERVICE_SECRET/versions/latest"
        path: "API_SERVICE_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/AWS_ACCESS_KEY_ID/versions/latest"
        path: "AWS_ACCESS_KEY_ID"
      - resourceName: "projects/blockjoy-staging/secrets/AWS_SECRET_ACCESS_KEY/versions/latest"
        path: "AWS_SECRET_ACCESS_KEY"
      - resourceName: "projects/blockjoy-staging/secrets/CF_TOKEN/versions/latest"
        path: "CF_TOKEN"
      - resourceName: "projects/blockjoy-staging/secrets/DATABASE_URL/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/blockjoy-staging/secrets/JWT_SECRET/versions/latest"
        path: "JWT_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/REFRESH_SECRET/versions/latest"
        path: "REFRESH_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/JWT_SECRET_FALLBACK/versions/latest"
        path: "JWT_SECRET_FALLBACK"
      - resourceName: "projects/blockjoy-staging/secrets/REFRESH_SECRET_FALLBACK/versions/latest"
        path: "REFRESH_SECRET_FALLBACK"
      - resourceName: "projects/blockjoy-staging/secrets/MQTT_PASSWORD/versions/latest"
        path: "MQTT_PASSWORD"
      - resourceName: "projects/blockjoy-staging/secrets/SENDGRID_API_KEY/versions/latest"
        path: "SENDGRID_API_KEY"
      - resourceName: "projects/blockjoy-staging/secrets/R2_URL/versions/latest"
        path: "STORAGE_URL"
      - resourceName: "projects/blockjoy-staging/secrets/STRIPE_SECRET/versions/latest"
        path: "STRIPE_SECRET"
      - resourceName: "projects/blockjoy-staging/secrets/STRIPE_WEBHOOK_SECRET/versions/latest"
        path: "STRIPE_WEBHOOK_SECRET"
      # FIXME: remove these after a proper secrets integration
      - resourceName: "projects/blockjoy-staging/secrets/CLOUDFLARE_CERT_KEY/versions/latest"
        path: "CLOUDFLARE_CERT_KEY"
      - resourceName: "projects/blockjoy-staging/secrets/GRAFANA_PROMETHEUS_KEY/versions/latest"
        path: "GRAFANA_PROMETHEUS_KEY"
      - resourceName: "projects/blockjoy-staging/secrets/GRAFANA_BASIC_AUTH_KEY/versions/latest"
        path: "GRAFANA_BASIC_AUTH_KEY"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockvisor-api-sa
  annotations:
    iam.gke.io/gcp-service-account: gke-workload@blockjoy-staging.iam.gserviceaccount.com
---

