apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: blockvisor-api-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/blockjoy-dev/secrets/SENDGRID_API_KEY/versions/latest"
        path: "SENDGRID_API_KEY"
      - resourceName: "projects/blockjoy-dev/secrets/REFRESH_SECRET/versions/latest"
        path: "REFRESH_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/PWD_RESET_SECRET/versions/latest"
        path: "PWD_RESET_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/API_SERVICE_SECRET/versions/latest"
        path: "API_SERVICE_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/JWT_SECRET/versions/latest"
        path: "JWT_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/CONFIRMATION_SECRET/versions/latest"
        path: "CONFIRMATION_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/DATABASE_URL/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/blockjoy-dev/secrets/INVITATION_SECRET/versions/latest"
        path: "INVITATION_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/COOKBOOK_TOKEN/versions/latest"
        path: "COOKBOOK_TOKEN"
      - resourceName: "projects/blockjoy-dev/secrets/COOKBOOK_URL/versions/latest"
        path: "COOKBOOK_URL"
      - resourceName: "projects/blockjoy-dev/secrets/EMQX_BASE_URL/versions/latest"
        path: "EMQX_BASE_URL"
      - resourceName: "projects/blockjoy-dev/secrets/EMQX_APP_ID/versions/latest"
        path: "EMQX_APP_ID"
      - resourceName: "projects/blockjoy-dev/secrets/EMQX_SECRET/versions/latest"
        path: "EMQX_SECRET"
      - resourceName: "projects/blockjoy-dev/secrets/MQTT_PASSWORD/versions/latest"
        path: "MQTT_PASSWORD"
      - resourceName: "projects/blockjoy-dev/secrets/MQTT_SERVER_PORT/versions/latest"
        path: "MQTT_SERVER_PORT"
      - resourceName: "projects/blockjoy-dev/secrets/MQTT_CLIENT_ID/versions/latest"
        path: "MQTT_CLIENT_ID"
      - resourceName: "projects/blockjoy-dev/secrets/MQTT_SERVER_ADDRESS/versions/latest"
        path: "MQTT_SERVER_ADDRESS"
      - resourceName: "projects/blockjoy-dev/secrets/MQTT_USERNAME/versions/latest"
        path: "MQTT_USERNAME"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blockvisor-api-sa
  annotations:
      iam.gke.io/gcp-service-account: gke-workload@blockjoy-dev.iam.gserviceaccount.com
---