steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-docker.pkg.dev/blockjoy-deployer/blockvisor-api/blockvisor-api-builder:latest', 
           './Dockerfile.builder']
images:
  - 'us-docker.pkg.dev/blockjoy-deployer/blockvisor-api/blockvisor-api-builder:latest'