name: Docker Build

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Docker build and push
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: us-docker.pkg.dev
          project_id: blockjoy-deployer
          image_name: blockvisor-api/dev-blockvisor-api
          image_tag: ${{ github.sha }},latest
          dockerfile: ./docker/Dockerfile
          context: .
