name: Local Build
on:
   push:
     branches: [main, ci/gcr]
jobs:
  build-and-push-to-gcr:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        #- name: Set up QEMU
        #  uses: docker/setup-qemu-action@v2
        #- name: Set up Docker Buildx
        #  uses: docker/setup-buildx-action@v2
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Build and Push API
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: us-docker.pkg.dev
          project_id: blockjoy-deployer
          image_name: blockvisor-api/dev-blockvisor-api
          image_tag: ${{ github.sha }},latest
          dockerfile: ./Dockerfile
          context: ./
