name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on:
      group: Docker

    env:
      CONFIG_FILE: "${{ github.workspace }}/blockvisor-api/config.toml"

    services:
      postgres:
        image: postgres:13-bookworm
        env:
          POSTGRES_DB: blockvisor_db
          POSTGRES_USER: blockvisor
          POSTGRES_PASSWORD: password
        ports:
          - 25432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mqtt:
        image: emqx/emqx-enterprise:5.3.0
        ports:
          - 21883:1883
        volumes:
          - ${{ github.workspace }}/docker/emqx:/opt/emqx/etc

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          apt update
          apt install -y libpq-dev libssl-dev pkg-config
          export PB_URL=https://github.com/protocolbuffers/protobuf/releases
          curl -LO $PB_URL/download/v29.3/protoc-29.3-linux-x86_64.zip
          unzip -o protoc-29.3-linux-x86_64.zip -d proto
          rm -rf /usr/local/include/google
          mv proto/bin/protoc /usr/local/bin
          mv proto/include/google /usr/local/include
          export SC_URL=https://github.com/mozilla/sccache/releases
          export SC_DIST=sccache-dist-v0.9.1-x86_64-unknown-linux-musl
          curl -LO $SC_URL/download/v0.9.1/$SC_DIST.tar.gz
          tar -xvf $SC_DIST.tar.gz
          mv $SC_DIST/sccache-dist /usr/local/bin/sccache
          chmod +x /usr/local/bin/sccache

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cargo tests
        run: |
          cargo clippy --all-features --all-targets -- -Dwarnings -Drust-2018-idioms
          cargo fmt --all -- --check
          sccache cargo test --all-features --no-fail-fast --jobs 1
