name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on:
      group: Docker
      labels: docker

    env:
      CONFIG_FILE: "${{ github.workspace }}/blockvisor-api/config.toml"

    services:
      postgres:
        image: postgres:13-bookworm
        env:
          POSTGRES_DB: blockvisor_db
          POSTGRES_USER: blockvisor
          POSTGRES_PASSWORD: password
        ports:
          - 25432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mqtt:
        image: emqx/emqx-enterprise:5.3.0
        ports:
          - 21883:1883
        volumes:
          - ${{ github.workspace }}/docker/emqx:/opt/emqx/etc

      vault:
        image: hashicorp/vault:1.17
        ports:
          - 28200:8200
        env:
          SKIP_SETCAP: true
          VAULT_ADDR: "http://0.0.0.0:8200"
          VAULT_DEV_ROOT_TOKEN_ID: "vault-root-token"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install packages
        run: >
          apt update
          && apt install -y libpq-dev

      - name: Initialize vault
        run: >
          curl
          --request POST
          --header "X-Vault-Token: vault-root-token"
          --data '{"type":"kv","options":{"version":"2"}}'
          http://localhost:28200/v1/sys/mounts/blockjoy

      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: dtolnay/rust-toolchain@stable

      - name: Cargo tests
        run: >
          cargo clippy --all-features --all-targets -- -Dwarnings -Drust-2018-idioms
          && cargo fmt --all -- --check
          && cargo test --all-features --no-fail-fast --jobs 1
