name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17.4
        env:
          POSTGRES_DB: blockvisor_db
          POSTGRES_USER: blockvisor
          POSTGRES_PASSWORD: password
        ports:
          - 5432
        options: >-
          --name postgres
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mqtt:
        image: emqx/emqx-enterprise:5.8.5
        options: --name mqtt
        ports:
          - 1883

    steps:
      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE
          sudo chmod -R 755 $GITHUB_WORKSPACE

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libpq-dev libssl-dev pkg-config
          PROTO_URL=https://github.com/protocolbuffers/protobuf/releases/download/v29.3/protoc-29.3-linux-x86_64.zip
          curl -L $PROTO_URL -o protoc.zip
          unzip -o protoc.zip -d protoc
          rm -rf /usr/local/include/google
          sudo mv protoc/bin/* /usr/local/bin
          sudo mv protoc/include/google /usr/local/include/

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cargo tests
        env:
          CONFIG_FILE: "${{ github.workspace }}/blockvisor-api/config.toml"
          DATABASE_URL: "postgres://blockvisor:password@localhost:${{ job.services.postgres.ports['5432'] }}/blockvisor_db"
          MQTT_SERVER_PORT: "${{ job.services.mqtt.ports['1883'] }}"
        run: |
          cargo clippy --all-features --all-targets -- -Dwarnings -Drust-2018-idioms
          cargo fmt --all -- --check
          cargo test --all-features --no-fail-fast --jobs 1
